title: Datamatiker
description: Opgaver og information omkring datamatikeruddannelsen på Professionshøjskolen UCN
author: "Brian Hvarregaard"

theme: minimal

base_url: /Datamatiker
repository: brhvucn/Datamatiker
