title: Datamatiker
description: Opgaver og information omkring datamatikeruddannelsen på Professionshøjskolen UCN
author: "Brian Hvarregaard"

remote_theme: just-the-docs/just-the-docs
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

base_url: /Datamatiker
repository: brhvucn/Datamatiker

# Minima social links
github_username: brhvucn
