title: Datamatiker
description: Opgaver og information omkring datamatikeruddannelsen på Professionshøjskolen UCN
author: "Brian Hvarregaard"

theme: minima

base_url: /Datamatiker
repository: brhvucn/Datamatiker

# Minima social links
github_username: brhvucn
